system_prompt: |
  Think step by step.
  Evaluate the truthfulness of the following text.
  To do this, you will assess three criteria:
  1. Source credibility (SC_val, 0-1)
  2. Multiple confirmation (MC_val, 0-1)
  3. Evidence support (ES_val, 0-1)
  The final truth score should be a value between 0 and 1.
  Return the score in [0,1] at the end of the response after a separator ####.
format: |
  Q: {question}
  A: {answer}
fewshot: 
  - question: |
      Is that the Eiffel Tower lit up in Pakistan colours  LahoreBlast LahoreAttack EasterSunday PrayForPakistan
    answer: |
      1. SC_val-Reasoning: The message lacks a clear or authoritative source (e.g., official statement from Paris authorities or Eiffel Tower management). The use of hashtags suggests social media origin rather than verified news. Score: 0.15,
      2. MC_val-Reasoning: No corroborating reports from independent sources (e.g., French media outlets, international news agencies). The claim about the Eiffel Tower lighting is not supported by reliable channels. Score: 0.1,
      3. ES_val-Reasoning: ES_val-Reasoning: Visual evidence appears to be manipulated or misattributed, with no credible documentation of such lighting occurring. The connection to the Lahore attack is speculative. Score: 0.05.
      Calculation: (0.15 + 0.1 + 0.05) / 3 = 0.1.
      #### 0.1
  - question: | 
      NY The City and the Storm The Look of PostSandy New York
    answer: |
      1. SC_val-Reasoning: The statement references a well-documented historical event (Hurricane Sandy) likely reported by official weather agencies and mainstream media. Score: 0.9,
      2. MC_val-Reasoning: Multiple independent news sources and government reports have extensively covered the hurricane's impact on New York. Score: 0.95,
      3. ES_val-Reasoning: Comprehensive photographic, video and official records exist documenting the storm's effects on New York City. Score: 0.85.
      Calculation: (0.9 + 0.95 + 0.85) / 3 = 0.9.
      #### 0.9
  - question: |
      Detailed photos of Xiang Lius tendon surgery exposed Stop complaints and please show sympathy and blessings
    answer: |
      1. SC_val-Reasoning: Official or mainstream media outlets likely reported the surgery, and these sources have high credibility.Score: 0.8,
      2. MC_val-Reasoning: Multiple independent news sources or channels have likely corroborated and confirmed this information.Score: 0.85,
      3. ES_val-Reasoning: Detailed photos from the surgery site have likely circulated widely online and on social media.Score: 0.9.
      Calculation: (0.8 + 0.85 + 0.9) / 3 = 0.85.
      #### 0.85
  - question: |
      Tianyi Li’s successful exoneration! Just received news that the owner of the "rivuai160" bar in Sanlitun has been taken into custody by the police. The authorities have initiated a prostitution investigation on the bar. Tianyi Li and five others are expected to shift from being defendants to witnesses, potentially being released as soon as this weekend!
    answer: |
      1. SC_val-Reasoning: The message lacks a clear or authoritative source (e.g., official news outlet, police statement).The phrasing ("Breaking News," "Just received news") is typical of unverified rumors or social media posts.Score: 0.2,
      2. MC_val-Reasoning: No corroborating reports from independent sources (e.g., other news agencies, government announcements).Claims about "Tianyi Li" and the bar investigation are not widely discussed in reliable channels.Score: 0.1,
      3. ES_val-Reasoning: Key details (e.g., "shift from defendants to witnesses," "release this weekend") are speculative with no documented proof.The bar’s name ("rivuai160") and location (Sanlitun) could be fabricated or exaggerated, as no public records support this claim.Score: 0.1.
      Calculation: (0.2 + 0.1 + 0.1) / 3 = 0.13.
      #### 0.13