system_prompt: |
  Think step by step to evaluate the truthfulness of the following text.
  To do this, you will assess three criteria:
  1. Source credibility (SC_val, a value between 0 and 1)
  2. Multiple confirmation (MC_val, a value between 0 and 1)
  3. Evidence support (ES_val, a value between 0 and 1)

  Your response should clearly state the score for each criterion (SC_val, MC_val, ES_val), including a brief reasoning for each score.
  Then, show the calculation for the final truth score, which is the average of these three scores: (SC_val + MC_val + ES_val) / 3.
  The final truth score should be a value between 0 and 1.
  Return the answer at the end of the response after a separator ####.
format: |
  Q: {question}
  A: {answer}
fewshot: 
  - question: |
      Is that the Eiffel Tower lit up in Pakistan colours  LahoreBlast LahoreAttack EasterSunday PrayForPakistan
    answer: |
      1. SC_val=0.1 (Reasoning: The claim primarily spread on social media from unverified accounts, lacking corroboration from official sources or reputable news.), 2. MC_val=0.0 (Reasoning: No reputable, independent sources confirmed the claim; instead, it was widely debunked by fact-checking organizations.), 3. ES_val=0.0 (Reasoning: Images/videos used were typically old, manipulated, or misattributed, with no authentic evidence supporting this specific event context.). Calculation: (0.1 + 0.0 + 0.0) / 3 = 0.03.
      #### 0.03
  - question: | 
      If there are 3 cars in the parking lot and 2 more cars arrive, how many
      cars are in the parking lot?
    answer: |
      There are originally 3 cars. 2 more cars arrive. 3 + 2 = 5. #### 5
  - question: |
      Leah had 32 chocolates and her sister had 42. If they ate 35, how many
      pieces do they have left in total?
    answer: |
      Originally, Leah had 32 chocolates. Her sister had 42. So in total they
      had 32 + 42 = 74. After eating 35, they had 74 - 35 = 39. #### 39
  - question:
      Jason had 20 lollipops. He gave Denny some lollipops. Now Jason has 12
      lollipops. How many lollipops did Jason give to Denny?
    answer: |
      Jason started with 20 lollipops. Then he had 12 after giving some to Denny.
      So he gave Denny 20 - 12 = 8. #### 8
  - question: |
      Shawn has five toys. For Christmas, he got two toys each from his mom and
      dad. How many toys does he have now?
    answer: |
      Shawn started with 5 toys. If he got 2 toys each from his mom and dad,
      then that is 4 more toys. 5 + 4 = 9. #### 9
  - question: |
      There were nine computers in the server room. Five more computers were
      installed each day, from monday to thursday. How many computers are now in the
      server room?
    answer: |
      There were originally 9 computers. For each of 4 days, 5 more computers
      were added. So 5 * 4 = 20 computers were added. 9 + 20 is 29. #### 29
  - question: |
      Michael had 58 golf balls. On tuesday, he lost 23 golf balls. On wednesday,
      he lost 2 more. How many golf balls did he have at the end of wednesday?
    answer: |
      Michael started with 58 golf balls. After losing 23 on tuesday, he had
      58 - 23 = 35. After losing 2 more, he had 35 - 2 = 33 golf balls. #### 33
  - question: |
      Olivia has $23. She bought five bagels for $3 each. How much money does
      she have left
    answer: |
      Olivia had 23 dollars. 5 bagels for 3 dollars each will be 5 x 3 = 15
      dollars. So she has 23 - 15 dollars left. 23 - 15 is 8. #### 8