system_prompt: |
  Think step by step, but only keep minimum draft for each thinking step, with 5 words at most.
  Evaluate the truthfulness of the following text.
  To do this, you will assess three criteria:
  1. Source credibility (SC_val, 0-1)
  2. Multiple confirmation (MC_val, 0-1)
  3. Evidence support (ES_val, 0-1)
  The final truth score should be a value between 0 and 1.
  Return the score in [0,1] at the end of the response after a separator ####.
format: |
  Q: {question}
  A: {answer}
fewshot:
  - question: |
      Is that the Eiffel Tower lit up in Pakistan colours  LahoreBlast LahoreAttack EasterSunday PrayForPakistan
    answer: |
      1. SC_val-Reasoning: Unverified social media, no official news.Score: 0.15,
      2. MC_val-Reasoning: Unconfirmed by reputable sources, debunked.Score: 0.1,
      3. ES_val-Reasoning: Old/manipulated media, no authentic evidence.Score: 0.05.
      Calculation: (0.15 + 0.1 + 0.05) / 3 = 0.1.
      #### 0.1
  - question: |
      NY The City and the Storm The Look of PostSandy New York
    answer: |
      1. SC_val-Reasoning: Reputable source/official report likely.Score: 0.9,
      2. MC_val-Reasoning: Widely confirmed by news/official sources.Score: 0.95,
      3. ES_val-Reasoning: Abundant photo/video/data evidence.Score: 0.85.
      Calculation: (0.9 + 0.95 + 0.85) / 3 = 0.9.
      #### 0.9
  - question: |
      Detailed photos of Xiang Lius tendon surgery exposed Stop complaints and please show sympathy and blessings
    answer: |
      1. SC_val-Reasoning: Official/media likely reported surgery.Score: 0.8,
      2. MC_val-Reasoning: Multiple outlets likely confirmed.Score: 0.85,
      3. ES_val-Reasoning: Surgery photos likely circulated.Score: 0.9.
      Calculation: (0.8 + 0.85 + 0.9) / 3 = 0.85.
      #### 0.85
  - question: |
      Tianyi Li’s successful exoneration! Just received news that the owner of the "rivuai160" bar in Sanlitun has been taken into custody by the police. The authorities have initiated a prostitution investigation on the bar. Tianyi Li and five others are expected to shift from being defendants to witnesses, potentially being released as soon as this weekend!
    answer: |
      #### 0.1