system_prompt: |
  逐步思考。
  评估以下文本的真实性，
  为此需评估三个标准：
  1 来源可信度（SC_val 0-1）
  2 多方确认（MC_val 0-1）
  3 证据支持（ES_val 0-1）
  最终评分为[0,1]值
  末尾用分隔符####返回评分，不附加任何解释或额外信息。
format: |
  Q: {question}
  A: {answer}
fewshot: 
  - question: |
      这是以巴基斯坦颜色点亮的埃菲尔铁塔吗 拉合尔爆炸 拉合尔袭击 复活节周日 为巴基斯坦祈祷
    answer: |
      1 SC_val推理：消息缺乏明确权威来源（如巴黎官方或埃菲尔铁塔管理方声明），使用话题标签表明源自社交媒体而非权威新闻。得分：0.15
      2 MC_val推理：无独立消息源佐证（如法国媒体、国际新闻机构），可靠渠道均未支持铁塔亮灯说法。得分：0.1
      3 ES_val推理：视觉证据存在篡改或误用嫌疑，无可靠记录证明该灯光事件，与拉合尔袭击的关联具推测性。得分：0.05
      计算：(0.15+0.1+0.05)/3=0.1
      #### 0.1
  - question: | 
      纽约市与风暴桑迪飓风后的纽约景象
    answer: |
      1 SC_val推理：陈述涉及有完备记录的历史事件（桑迪飓风），气象部门和主流媒体均有报道。得分：0.9
      2 MC_val推理：多家独立新闻源和政府报告详细记载了飓风对纽约的影响。得分：0.95
      3 ES_val推理：存在大量照片、视频及官方档案记录风暴对纽约市的影响。得分：0.85
      计算：(0.9+0.95+0.85)/3=0.9
      #### 0.9
  - question: |
      详细照片曝光刘翔肌腱手术过程 停止抱怨请给予同情和祝福
    answer: |
      1 SC_val推理：官方或主流媒体可能报道该手术，此类信源可信度高 得分：0.8
      2 MC_val推理：多家独立新闻来源或渠道可能已交叉验证此信息 得分：0.85
      3 ES_val推理：手术现场详细照片可能已在网络及社交媒体广泛流传 得分：0.9
      计算：(0.8+0.85+0.9)/3=0.85
      #### 0.85
  - question: |
      李天一成功脱罪！刚获知北京三里屯"rivuai160"酒吧老板已被警方拘留。当局已对该酒吧启动卖淫调查。李天一等六人将从被告转为证人，最快本周末释放！
    answer: |
      1 SC_val推理：消息缺乏权威信源（如官方通报、警方声明），措辞（"突发新闻"、"刚获知"）符合未证实传闻特征。得分：0.2
      2 MC_val推理：无独立信源交叉验证（如其他新闻机构、政府公告），可靠渠道未见"李天一"及酒吧调查的相关讨论。得分：0.1
      3 ES_val推理：关键细节（"被告转证人"、"周末释放"）无实证支持，酒吧名称"rivuai160"及三里屯位置缺乏公开记录佐证。得分：0.1
      计算：(0.2 + 0.1 + 0.1) / 3 = 0.13
      #### 0.13