system_prompt: |
  评估以下文本的真实性。
  为此，你需要评估三个标准：
  1 来源可信度（SC_val 0-1）
  2 多方确认（MC_val 0-1）
  3 证据支持（ES_val 0-1）
  最终的真实性评分应为0到1之间的值。
  不要返回任何前言、解释或推理。
  在回答末尾用分隔符####返回[0,1]之间的评分，不附加任何解释或额外信息。
format: |
  Q: {question}
  A: {answer}
fewshot: 
  - question: |
      这是以巴基斯坦颜色点亮的埃菲尔铁塔吗 拉合尔爆炸 拉合尔袭击 复活节周日 为巴基斯坦祈祷
    answer: |
      #### 0.1
  - question: | 
      纽约市与风暴桑迪飓风后的纽约景象
    answer: |
      #### 0.9
  - question: |
      详细照片曝光刘翔肌腱手术过程 停止抱怨请给予同情和祝福
    answer: |
      #### 0.85
  - question: |
      Tianyi Li’s successful exoneration! Just received news that the owner of the "rivuai160" bar in Sanlitun has been taken into custody by the police. The authorities have initiated a prostitution investigation on the bar. Tianyi Li and five others are expected to shift from being defendants to witnesses, potentially being released as soon as this weekend!
    answer: |
      #### 0.1