system_prompt: |
  逐步思考，但每步仅保留最少草稿，每步最多5个字。
  评估以下文本的真实性，
  为此需评估三个标准：
  1 来源可信度（SC_val 0-1）
  2 多方确认（MC_val 0-1）
  3 证据支持（ES_val 0-1）
  最终评分为[0,1]值
  末尾用分隔符####返回评分，不附加任何解释或额外信息。
format: |
  Q: {question}
  A: {answer}
fewshot:
  - question: |
      这是以巴基斯坦颜色点亮的埃菲尔铁塔吗 拉合尔爆炸 拉合尔袭击 复活节周日 为巴基斯坦祈祷
    answer: |
      1 SC_val推理：未验证社交媒体，无官方消息 评分：0.15
      2 MC_val推理：无权威确认，已证伪 评分：0.1
      3 ES_val推理：旧/篡改素材，无真实证据 评分：0.05
      计算：(0.15+0.1+0.05)/3=0.1
      #### 0.1
  - question: |
      纽约市与风暴桑迪飓风后的纽约景象
    answer: |
      1 SC_val推理：可信来源/官方报告 评分：0.9
      2 MC_val推理：广泛获新闻/官方确认 评分：0.95
      3 ES_val推理：大量照片/视频证据 评分：0.85
      计算：(0.9+0.95+0.85)/3=0.9
      #### 0.9
  - question: |
      详细照片曝光刘翔肌腱手术过程 停止抱怨请给予同情和祝福
    answer: |
      1 SC_val推理：官方/媒体可能报道 评分：0.8
      2 MC_val推理：多渠道可能确认 评分：0.85
      3 ES_val推理：手术照片或存在 评分：0.9
      计算：(0.8+0.85+0.9)/3=0.85
      #### 0.85
  - question: |
      Tianyi Li’s successful exoneration! Just received news that the owner of the "rivuai160" bar in Sanlitun has been taken into custody by the police. The authorities have initiated a prostitution investigation on the bar. Tianyi Li and five others are expected to shift from being defendants to witnesses, potentially being released as soon as this weekend!
    answer: |
      #### 0.1